### ISSUE TITLE
Jinja2 >=3.0 compatibility (DeprecationWarnings)

### ISSUE THREAD

**Issue by Cheaterman** [lepture/flask-wtf#439] opened 2021-05-20 14:18 UTC
Hello! Everything in the title :-)

Today my CI broke (pytest treats warnings as errors by default), here is why:

```
/env/lib/python3.8/site-packages/jinja2/runtime.py:828: in _invoke
    rv = self._func(*arguments)
unityretail/templates/form_helpers.html:2: in template
    {{ form.hidden_tag() }}
/env/lib/python3.8/site-packages/flask_wtf/form.py:133: in hidden_tag
    return Markup(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cls = <class 'jinja2.utils.Markup'>, base = '', encoding = None
errors = 'strict'
    def __new__(cls, base="", encoding=None, errors="strict"):  # type: ignore
>       warnings.warn(
            "'jinja2.Markup' is deprecated and will be removed in Jinja"
            " 3.1. Import 'markupsafe.Markup' instead.",
            DeprecationWarning,
            stacklevel=2,
        )
E       DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
/env/lib/python3.8/site-packages/jinja2/utils.py:838: DeprecationWarning
```

Sorry I can't PR that just yet (pinned flask<2.0 instead) but I'm guessing this is a flask-wtf issue? At least in the sense that it could conceivably be addressed here, by importing the Markup class from different modules depending on Jinja2 version?

Thanks for your attention :-)

**Comment by davidism** [comment] 2021-05-20 14:20
Duplicate of #435.

**Closed by davidism** 2021-05-20 14:20 UTC
