### ISSUE TITLE
DeprecationWarning for jinja2.Markup

### ISSUE THREAD

**Issue by gregersn** [lepture/flask-wtf#435] opened 2021-05-12 21:48 UTC
```
flask_wtf/form.py:133: DeprecationWarning: 'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
    return Markup(
    ```

**Comment by davidism** [comment] 2021-05-12 22:07
duplicate of #434

**Closed by davidism** 2021-05-12 22:07 UTC
