### ISSUE TITLE
Form.wrap_formdata does not work correctly with BooleanField

### ISSUE THREAD

**Issue by nfvs** [lepture/flask-wtf#322] opened 2018-01-11 16:32 UTC
https://github.com/lepture/flask-wtf/blob/master/flask_wtf/form.py#L64

`Form.wrap_formdata()`, which gets called from wtforms, will return a wrapper with json values; however, BooleanField only gets set to False with strings, not with booleans:

https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L699

Ideally wtforms would also support `False` values in form values.

**Comment by davidism** [comment] 2018-01-11 16:50
Duplicate of wtforms/wtforms#369. There's not a lot Flask-WTF can do here, WTForms is only really designed to handle string form data. The PR you opened seems fine, but note that WTForms is unlikely to get a new release unless I can get in contact with the maintainers again.

**Closed by davidism** 2018-01-11 16:50 UTC

**Comment by nfvs** [comment] 2018-01-11 16:53
@davidism you seem to have write access though. This is an exceptionally common case, you can find tons of StackOverflow threads about it, and even your suggestions don't work:

> You need to pass your data, as a MultiDict, to prevent the automatic behavior
> form = MyForm(MultiDict(data))

https://stackoverflow.com/a/37125336/86387

```python
>>> class MyForm(wtforms.Form):
...   s = wtforms.StringField(validators=[InputRequired()])
...   b = wtforms.BooleanField(validators=[InputRequired()])
...
>>> f = MyForm(MultiDict({'s': 'S', 'b': False}))
>>> f.data
{'s': 'S', 'b': True}
```

That's clearly broken behaviour I'd say.

**Comment by davidism** [comment] 2018-01-11 17:02
I have write access to the repo. I have no access to any other infrastructure needed to make releases.

The multidict answer is about passing a dict instead of a multidict, not about passing JSON data.

**Comment by nfvs** [comment] 2018-01-11 17:05
Understood, but even just having it merged would be an improvement since we can install packages from git. Even having a "2.2-rc" branch would be better than the current broken functionality :-(
