### ISSUE TITLE
validate_on_submit() expects a tuple list for SelectField even though a normal list is a valid argument

### ISSUE THREAD

**Issue by hakanohi** [lepture/flask-wtf#417] opened 2020-07-29 13:46 UTC
### Actual Behavior
`form.validate on submit()` evaluates to `False` when `choices` in `SelectField` is a list of values only. The same form validation evaluates to  `True` when using `(value, label)` tuples as used with version 2.2.1
```python

class RegistrationForm(FlaskForm):

    language = SelectField('Language', choices=['python', 'ruby', 'rust'], validators=[DataRequired()])
    submit = SubmitField('Submit')


@app.route('/', methods=['GET', 'POST'])
def index():
    form = RegistrationForm()
    if form.validate_on_submit():
        return redirect(url_for('test'))
    return render_template('index.html', form=form)
```
The `SelectField()` is rendered properly in the HTML form and its value can be accessed with `form.language.data` but `form.validate_on_submit()` still evaluates to `False`.
### Expected Behavior
`form.validate on submit()` to evaluate to `True` when `choices` in `SelectField` is a list of values only as well.

### Environment

* Python version: 3.8.2
* Flask-wtf version: 0.14.3
* wtforms version: 2.3.1

**Comment by davidism** [comment] 2020-07-29 14:03
Duplicate of https://github.com/wtforms/wtforms/pull/598

**Closed by davidism** 2020-07-29 14:03 UTC
